/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.faedocaminhoes.gui;

import  br.com.faedocaminhoes.connection.ConnectionFactory;
import br.com.faedocaminhoes.model.service.AbastecimentoService;
import br.com.faedocaminhoes.model.service.CategoriaService;
import br.com.faedocaminhoes.model.service.FornecedorService;
import br.com.faedocaminhoes.model.service.PessoaService;
import br.com.faedocaminhoes.model.service.ProdutoService;
import br.com.faedocaminhoes.model.service.UsuarioService;
import br.com.faedocaminhoes.model.service.VeiculoService;
import br.com.faedocaminhoes.uteis.DimensionFrame;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.LineBorder;

/**
 *
 * @author Mikeias
 */
public class MainGUI extends DimensionFrame {

    /**
     * Creates new form Main
     */
    public MainGUI() {
        initComponents();
        setIco();

        //INICIAR CONEXÃO COM BANCO DE DADOS
        EntityManager em = new ConnectionFactory().getConection();

        // LISTENER FECHAR APLICAÇÃO
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                int conf = JOptionPane.showConfirmDialog(MainGUI.this, "Deseja sair da aplicação?", "FAEDO CAMINHÕES ©", JOptionPane.YES_NO_OPTION);
                if (conf == JOptionPane.YES_OPTION) {
                    System.exit(0);
                } else {
                    e.getOldState();
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panePrincipal = new javax.swing.JPanel();
        paneMenu = new javax.swing.JPanel();
        Menu = new javax.swing.JTabbedPane();
        abaArquivo = new javax.swing.JPanel();
        lblArqParametros = new javax.swing.JLabel();
        lblArqSair = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblArqBackup = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        abaPessas = new javax.swing.JPanel();
        lblCadPessoa = new javax.swing.JLabel();
        lblCadUsuario = new javax.swing.JLabel();
        lblCadCidade = new javax.swing.JLabel();
        lblCadEstados = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblCadFornecedor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblConsumoGas = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblAddConsumo = new javax.swing.JLabel();
        abaProdutos = new javax.swing.JPanel();
        lblCadProduto = new javax.swing.JLabel();
        lblCadCategoria = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCadMovimentacao = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        abaLancamentos = new javax.swing.JPanel();
        lblLancamento = new javax.swing.JLabel();
        lblBaixa = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        abaOS = new javax.swing.JPanel();
        abaRelatorios = new javax.swing.JPanel();
        paneApp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nextsoft Software");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panePrincipal.setLayout(new java.awt.BorderLayout());

        paneMenu.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        abaArquivo.setBackground(new java.awt.Color(255, 255, 255));

        lblArqParametros.setBackground(new java.awt.Color(255, 255, 255));
        lblArqParametros.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblArqParametros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArqParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Parametros_36px.png"))); // NOI18N
        lblArqParametros.setText("Parâmetros");
        lblArqParametros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblArqParametros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblArqParametros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArqParametrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArqParametrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArqParametrosMouseExited(evt);
            }
        });

        lblArqSair.setBackground(new java.awt.Color(255, 255, 255));
        lblArqSair.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblArqSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArqSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_SignOut_36px.png"))); // NOI18N
        lblArqSair.setText("Sair");
        lblArqSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblArqSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblArqSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArqSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArqSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArqSairMouseExited(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblArqBackup.setBackground(new java.awt.Color(255, 255, 255));
        lblArqBackup.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblArqBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArqBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Backup_36px.png"))); // NOI18N
        lblArqBackup.setText("Backup");
        lblArqBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblArqBackup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblArqBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArqBackupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArqBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArqBackupMouseExited(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout abaArquivoLayout = new javax.swing.GroupLayout(abaArquivo);
        abaArquivo.setLayout(abaArquivoLayout);
        abaArquivoLayout.setHorizontalGroup(
            abaArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArquivoLayout.createSequentialGroup()
                .addComponent(lblArqParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArqBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArqSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 934, Short.MAX_VALUE))
        );
        abaArquivoLayout.setVerticalGroup(
            abaArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArquivoLayout.createSequentialGroup()
                .addGroup(abaArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArqSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblArqParametros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblArqBackup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Arquivo", abaArquivo);

        abaPessas.setBackground(new java.awt.Color(255, 255, 255));

        lblCadPessoa.setBackground(new java.awt.Color(255, 255, 255));
        lblCadPessoa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Team_36px.png"))); // NOI18N
        lblCadPessoa.setText("Pessoa");
        lblCadPessoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadPessoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadPessoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadPessoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadPessoaMouseExited(evt);
            }
        });

        lblCadUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblCadUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_User_36px.png"))); // NOI18N
        lblCadUsuario.setText("Usuario");
        lblCadUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseExited(evt);
            }
        });

        lblCadCidade.setBackground(new java.awt.Color(255, 255, 255));
        lblCadCidade.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Cidade_36px.png"))); // NOI18N
        lblCadCidade.setText("Cidade");
        lblCadCidade.setEnabled(false);
        lblCadCidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadCidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadCidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadCidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadCidadeMouseExited(evt);
            }
        });

        lblCadEstados.setBackground(new java.awt.Color(255, 255, 255));
        lblCadEstados.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadEstados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Cidade_36px.png"))); // NOI18N
        lblCadEstados.setText("Estado");
        lblCadEstados.setEnabled(false);
        lblCadEstados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadEstados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadEstadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadEstadosMouseExited(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCadFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        lblCadFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Team_36px.png"))); // NOI18N
        lblCadFornecedor.setText("Fornecedor");
        lblCadFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadFornecedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadFornecedorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout abaPessasLayout = new javax.swing.GroupLayout(abaPessas);
        abaPessas.setLayout(abaPessasLayout);
        abaPessasLayout.setHorizontalGroup(
            abaPessasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPessasLayout.createSequentialGroup()
                .addComponent(lblCadPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 792, Short.MAX_VALUE))
        );
        abaPessasLayout.setVerticalGroup(
            abaPessasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPessasLayout.createSequentialGroup()
                .addGroup(abaPessasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadPessoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblCadUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblCadCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblCadEstados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblCadFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        Menu.addTab("Pessoas", abaPessas);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblConsumoGas.setBackground(new java.awt.Color(255, 255, 255));
        lblConsumoGas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblConsumoGas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsumoGas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Abastecimento_36px.png"))); // NOI18N
        lblConsumoGas.setText("Adicionar");
        lblConsumoGas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblConsumoGas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblConsumoGas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsumoGasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsumoGasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsumoGasMouseExited(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAddConsumo.setBackground(new java.awt.Color(255, 255, 255));
        lblAddConsumo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAddConsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/All_Abastecimento_36px.png"))); // NOI18N
        lblAddConsumo.setText("Lancamentos");
        lblAddConsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddConsumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAddConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddConsumoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddConsumoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddConsumoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblConsumoGas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 981, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumoGas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Consumo", jPanel1);

        abaProdutos.setBackground(new java.awt.Color(255, 255, 255));

        lblCadProduto.setBackground(new java.awt.Color(255, 255, 255));
        lblCadProduto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Produto_36px.png"))); // NOI18N
        lblCadProduto.setText("Produto");
        lblCadProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadProdutoMouseExited(evt);
            }
        });

        lblCadCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCadCategoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Categoria_36px.png"))); // NOI18N
        lblCadCategoria.setText("Categoria");
        lblCadCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadCategoriaMouseExited(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCadMovimentacao.setBackground(new java.awt.Color(255, 255, 255));
        lblCadMovimentacao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadMovimentacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadMovimentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Movimentacao_36px.png"))); // NOI18N
        lblCadMovimentacao.setText(" Movimentações ");
        lblCadMovimentacao.setEnabled(false);
        lblCadMovimentacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCadMovimentacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCadMovimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadMovimentacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadMovimentacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadMovimentacaoMouseExited(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout abaProdutosLayout = new javax.swing.GroupLayout(abaProdutos);
        abaProdutos.setLayout(abaProdutosLayout);
        abaProdutosLayout.setHorizontalGroup(
            abaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaProdutosLayout.createSequentialGroup()
                .addComponent(lblCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadMovimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 908, Short.MAX_VALUE))
        );
        abaProdutosLayout.setVerticalGroup(
            abaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaProdutosLayout.createSequentialGroup()
                .addGroup(abaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaProdutosLayout.createSequentialGroup()
                        .addGroup(abaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        Menu.addTab("Estoque", abaProdutos);

        abaLancamentos.setBackground(new java.awt.Color(255, 255, 255));

        lblLancamento.setBackground(new java.awt.Color(255, 255, 255));
        lblLancamento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLancamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_List_36px.png"))); // NOI18N
        lblLancamento.setText("Lancamento");
        lblLancamento.setEnabled(false);
        lblLancamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLancamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLancamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLancamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLancamentoMouseExited(evt);
            }
        });

        lblBaixa.setBackground(new java.awt.Color(255, 255, 255));
        lblBaixa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblBaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/Add_Pagamento_36px.png"))); // NOI18N
        lblBaixa.setText("Baixa");
        lblBaixa.setEnabled(false);
        lblBaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblBaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBaixaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBaixaMouseExited(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout abaLancamentosLayout = new javax.swing.GroupLayout(abaLancamentos);
        abaLancamentos.setLayout(abaLancamentosLayout);
        abaLancamentosLayout.setHorizontalGroup(
            abaLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaLancamentosLayout.createSequentialGroup()
                .addComponent(lblLancamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1008, Short.MAX_VALUE))
        );
        abaLancamentosLayout.setVerticalGroup(
            abaLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator9)
        );

        Menu.addTab("Financeiro", abaLancamentos);

        abaOS.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout abaOSLayout = new javax.swing.GroupLayout(abaOS);
        abaOS.setLayout(abaOSLayout);
        abaOSLayout.setHorizontalGroup(
            abaOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        abaOSLayout.setVerticalGroup(
            abaOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Menu.addTab("Ordem de Serviços", abaOS);

        abaRelatorios.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout abaRelatoriosLayout = new javax.swing.GroupLayout(abaRelatorios);
        abaRelatorios.setLayout(abaRelatoriosLayout);
        abaRelatoriosLayout.setHorizontalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1151, Short.MAX_VALUE)
        );
        abaRelatoriosLayout.setVerticalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Menu.addTab("Relatorios", abaRelatorios);

        javax.swing.GroupLayout paneMenuLayout = new javax.swing.GroupLayout(paneMenu);
        paneMenu.setLayout(paneMenuLayout);
        paneMenuLayout.setHorizontalGroup(
            paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );
        paneMenuLayout.setVerticalGroup(
            paneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panePrincipal.add(paneMenu, java.awt.BorderLayout.NORTH);

        paneApp.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 105, 105));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/faedocaminhoes/icons/NFC_Logo_Preto_250px.png"))); // NOI18N
        jLabel1.setText("Next Software");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        paneApp.add(jLabel1, java.awt.BorderLayout.CENTER);

        panePrincipal.add(paneApp, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        //LoginGUI login = new LoginGUI(this, true);
        //login.setLocationRelativeTo(this);
        //login.setVisible(true);

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void lblBaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaixaMouseExited
        lblBaixa.setBackground(new Color(255, 255, 255));
        lblBaixa.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblBaixaMouseExited

    private void lblBaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaixaMouseEntered
        lblBaixa.setBackground(new Color(234, 236, 238));
        lblBaixa.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblBaixaMouseEntered

    private void lblLancamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLancamentoMouseExited
        lblLancamento.setBackground(new Color(255, 255, 255));
        lblLancamento.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblLancamentoMouseExited

    private void lblLancamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLancamentoMouseEntered
        lblLancamento.setBackground(new Color(234, 236, 238));
        lblLancamento.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblLancamentoMouseEntered

    private void lblCadCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCategoriaMouseExited
        lblCadCategoria.setBackground(new Color(255, 255, 255));
        lblCadCategoria.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadCategoriaMouseExited

    private void lblCadCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCategoriaMouseEntered
        lblCadCategoria.setBackground(new Color(234, 236, 238));
        lblCadCategoria.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadCategoriaMouseEntered

    private void lblCadProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadProdutoMouseExited
        lblCadProduto.setBackground(new Color(255, 255, 255));
        lblCadProduto.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadProdutoMouseExited

    private void lblCadProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadProdutoMouseEntered
        lblCadProduto.setBackground(new Color(234, 236, 238));
        lblCadProduto.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadProdutoMouseEntered

    private void lblCadUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseExited
        lblCadUsuario.setBackground(new Color(255, 255, 255));
        lblCadUsuario.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadUsuarioMouseExited

    private void lblCadUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseEntered
        lblCadUsuario.setBackground(new Color(234, 236, 238));
        lblCadUsuario.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadUsuarioMouseEntered

    private void lblCadPessoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPessoaMouseExited
        lblCadPessoa.setBackground(new Color(255, 255, 255));
        lblCadPessoa.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadPessoaMouseExited

    private void lblCadPessoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPessoaMouseEntered
        lblCadPessoa.setBackground(new Color(234, 236, 238));
        lblCadPessoa.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
        
    }//GEN-LAST:event_lblCadPessoaMouseEntered

    private void lblCadPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPessoaMouseClicked
        CadPessoaGUI cadCliente = new CadPessoaGUI(this, true, new PessoaService());
        cadCliente.setLocationRelativeTo(cadCliente);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_lblCadPessoaMouseClicked

    private void lblCadUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseClicked
        CadUsuarioGUI cadUsuario = new CadUsuarioGUI(this, true, new UsuarioService());
        cadUsuario.setLocationRelativeTo(cadUsuario);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_lblCadUsuarioMouseClicked

    private void lblCadProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadProdutoMouseClicked
        CadProdutoGUI cadProduto = new CadProdutoGUI(this, true, new ProdutoService(), new CategoriaService());
        cadProduto.setLocationRelativeTo(cadProduto);
        cadProduto.setVisible(true);
        
    }//GEN-LAST:event_lblCadProdutoMouseClicked

    private void lblCadCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCategoriaMouseClicked
        CadCategoriaGUI cadCategoria = new CadCategoriaGUI(this, true, new CategoriaService());
        cadCategoria.setLocationRelativeTo(cadCategoria);
        cadCategoria.setVisible(true);
        
    }//GEN-LAST:event_lblCadCategoriaMouseClicked

    private void lblLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLancamentoMouseClicked
        /*
        LancamentoGUI lancamento = new LancamentoGUI(this, true);
        lancamento.setLocationRelativeTo(lancamento);
        lancamento.setVisible(true);
        */
    }//GEN-LAST:event_lblLancamentoMouseClicked

    private void lblBaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaixaMouseClicked
        /*
        BaixaLancamentoGUI baixaLancamento = new BaixaLancamentoGUI(this, true);
        baixaLancamento.setLocationRelativeTo(baixaLancamento);
        baixaLancamento.setVisible(true);
        */
    }//GEN-LAST:event_lblBaixaMouseClicked

    private void lblCadCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCidadeMouseClicked
        /*
        CadCidade cadCidade = new CadCidade(this, true);
        cadCidade.setLocationRelativeTo(cadCidade);
        cadCidade.setVisible(true);
        */
    }//GEN-LAST:event_lblCadCidadeMouseClicked

    private void lblCadCidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCidadeMouseEntered
        lblCadCidade.setBackground(new Color(234, 236, 238));
        lblCadCidade.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadCidadeMouseEntered

    private void lblCadCidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCidadeMouseExited
        lblCadCidade.setBackground(new Color(255, 255, 255));
        lblCadCidade.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadCidadeMouseExited

    private void lblCadEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadEstadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadEstadosMouseClicked

    private void lblCadEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadEstadosMouseEntered
        lblCadEstados.setBackground(new Color(234, 236, 238));
        lblCadEstados.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadEstadosMouseEntered

    private void lblCadEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadEstadosMouseExited
        lblCadEstados.setBackground(new Color(255, 255, 255));
        lblCadEstados.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadEstadosMouseExited

    private void lblArqParametrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqParametrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblArqParametrosMouseClicked

    private void lblArqParametrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqParametrosMouseEntered
        lblArqParametros.setBackground(new Color(234, 236, 238));
        lblArqParametros.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblArqParametrosMouseEntered

    private void lblArqParametrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqParametrosMouseExited
        lblArqParametros.setBackground(new Color(255, 255, 255));
        lblArqParametros.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblArqParametrosMouseExited

    private void lblArqSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqSairMouseClicked
        int conf = JOptionPane.showConfirmDialog(MainGUI.this, "Deseja sair da aplicação?", "FAEDO CAMINHÕES ©", JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblArqSairMouseClicked

    private void lblArqSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqSairMouseEntered
        lblArqSair.setBackground(new Color(234, 236, 238));
        lblArqSair.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblArqSairMouseEntered

    private void lblArqSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqSairMouseExited
        lblArqSair.setBackground(new Color(255, 255, 255));
        lblArqSair.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblArqSairMouseExited

    private void lblCadMovimentacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadMovimentacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadMovimentacaoMouseClicked

    private void lblCadMovimentacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadMovimentacaoMouseEntered
        lblCadMovimentacao.setBackground(new Color(234, 236, 238));
        lblCadMovimentacao.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadMovimentacaoMouseEntered

    private void lblCadMovimentacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadMovimentacaoMouseExited
        lblCadMovimentacao.setBackground(new Color(255, 255, 255));
        lblCadMovimentacao.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadMovimentacaoMouseExited

    private void lblArqBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqBackupMouseClicked
        BackupGUI bkp = new BackupGUI();
        bkp.setLocationRelativeTo(bkp);
        bkp.setVisible(true);
    }//GEN-LAST:event_lblArqBackupMouseClicked

    private void lblArqBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqBackupMouseEntered
        lblArqBackup.setBackground(new Color(234, 236, 238));
        lblArqBackup.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblArqBackupMouseEntered

    private void lblArqBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqBackupMouseExited
        lblArqBackup.setBackground(new Color(255, 255, 255));
        lblArqBackup.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblArqBackupMouseExited

    private void lblConsumoGasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsumoGasMouseClicked
        CadAbastecimentoGUI cadAbastecimento = new CadAbastecimentoGUI(this, 
                                                                        true, 
                                                                        new AbastecimentoService(),
                                                                        new FornecedorService(),
                                                                        new ProdutoService(),
                                                                        new PessoaService(),
                                                                        new VeiculoService());
        cadAbastecimento.setLocationRelativeTo(cadAbastecimento);
        cadAbastecimento.setVisible(true);
    }//GEN-LAST:event_lblConsumoGasMouseClicked

    private void lblConsumoGasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsumoGasMouseEntered
        lblConsumoGas.setBackground(new Color(234, 236, 238));
        lblConsumoGas.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblConsumoGasMouseEntered

    private void lblConsumoGasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsumoGasMouseExited
        lblConsumoGas.setBackground(new Color(255, 255, 255));
        lblConsumoGas.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblConsumoGasMouseExited

    private void lblCadFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFornecedorMouseClicked
        CadFornecedorGUI cadFornecedor = new CadFornecedorGUI(this, true, new FornecedorService());
        cadFornecedor.setLocationRelativeTo(cadFornecedor);
        cadFornecedor.setVisible(true);
    }//GEN-LAST:event_lblCadFornecedorMouseClicked

    private void lblCadFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFornecedorMouseEntered
        lblCadFornecedor.setBackground(new Color(234, 236, 238));
        lblCadFornecedor.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblCadFornecedorMouseEntered

    private void lblCadFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFornecedorMouseExited
        lblCadFornecedor.setBackground(new Color(255, 255, 255));
        lblCadFornecedor.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblCadFornecedorMouseExited

    private void lblAddConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddConsumoMouseClicked
        AbastecimentoGUI cadAbastecimento = new AbastecimentoGUI(this, true, new AbastecimentoService(), new ProdutoService());
        cadAbastecimento.setLocationRelativeTo(cadAbastecimento);
        cadAbastecimento.setVisible(true);
    }//GEN-LAST:event_lblAddConsumoMouseClicked

    private void lblAddConsumoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddConsumoMouseEntered
        lblAddConsumo.setBackground(new Color(234, 236, 238));
        lblAddConsumo.setBorder(new LineBorder(new Color(160, 160, 160), 1, true));
    }//GEN-LAST:event_lblAddConsumoMouseEntered

    private void lblAddConsumoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddConsumoMouseExited
        lblAddConsumo.setBackground(new Color(255, 255, 255));
        lblAddConsumo.setBorder(new LineBorder(new Color(160, 160, 160), 0, true));
    }//GEN-LAST:event_lblAddConsumoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*
        //Synthetica
        try {
            //Configurar se deve aplicar o look a borda do JFrame  
            // No caso esta programado para não aplicar (Boolean.FALSE)  
            UIManager.put("Synthetica.window.decoration", Boolean.TRUE);
            //Configura qual Look você quer usar no projeto  
            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        JTattoo
        try {  
           //Configura o logo String dos JMenu's  
           Properties props = new Properties();  
           props.put("logoString", "FAEDO CAMINHÕES ©");  
           AeroLookAndFeel.setCurrentTheme(props);  
           //Configura o Look que deseja usar da Biblioteca JTattoo  
           UIManager.setLookAndFeel(new AeroLookAndFeel());  
        } catch (Exception erro) {  
           erro.printStackTrace();  
        }  
        */
         
        //Padrao para linux e windows
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        
         
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel abaArquivo;
    private javax.swing.JPanel abaLancamentos;
    private javax.swing.JPanel abaOS;
    private javax.swing.JPanel abaPessas;
    private javax.swing.JPanel abaProdutos;
    private javax.swing.JPanel abaRelatorios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAddConsumo;
    private javax.swing.JLabel lblArqBackup;
    private javax.swing.JLabel lblArqParametros;
    private javax.swing.JLabel lblArqSair;
    private javax.swing.JLabel lblBaixa;
    private javax.swing.JLabel lblCadCategoria;
    private javax.swing.JLabel lblCadCidade;
    private javax.swing.JLabel lblCadEstados;
    private javax.swing.JLabel lblCadFornecedor;
    private javax.swing.JLabel lblCadMovimentacao;
    private javax.swing.JLabel lblCadPessoa;
    private javax.swing.JLabel lblCadProduto;
    private javax.swing.JLabel lblCadUsuario;
    private javax.swing.JLabel lblConsumoGas;
    private javax.swing.JLabel lblLancamento;
    private javax.swing.JPanel paneApp;
    private javax.swing.JPanel paneMenu;
    private javax.swing.JPanel panePrincipal;
    // End of variables declaration//GEN-END:variables

    private void setIco() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
