/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.floatsolutions.gui;

import br.com.floatsolutions.model.Abastecimento;
import br.com.floatsolutions.model.Empresa;
import br.com.floatsolutions.model.Fornecedor;
import br.com.floatsolutions.model.Pessoa;
import br.com.floatsolutions.model.Produto;
import br.com.floatsolutions.model.Usuario;
import br.com.floatsolutions.model.Veiculo;
import br.com.floatsolutions.model.service.AbastecimentoService;
import br.com.floatsolutions.model.service.CategoriaService;
import br.com.floatsolutions.model.service.FornecedorService;
import br.com.floatsolutions.model.service.PessoaService;
import br.com.floatsolutions.model.service.ProdutoService;
import br.com.floatsolutions.model.service.VeiculoService;
import br.com.floatsolutions.uteis.JPaneError;
import br.com.floatsolutions.uteis.JTextFieldLetras;
import br.com.floatsolutions.uteis.JTextFieldNumeros;
import br.com.floatsolutions.uteis.ParseInteger;
import br.com.floatsolutions.uteis.UpperCase;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Poison
 */
public class CadAbastecimentoGUI extends javax.swing.JDialog {

    
    private Abastecimento abastecimento;
    private AbastecimentoService abastecimentoService;
    private Fornecedor fornecedor;
    private FornecedorService fornecedorService;
    private Produto produto;
    private ProdutoService produtoService;
    private Pessoa pessoa;
    private PessoaService pessoaService;
    private VeiculoService veiculoService;
    private NumberFormat moeda = new DecimalFormat("#,##0.000");
    private Usuario usuario;
    private Empresa empresa;
    
    private Locale c = Locale.US;
    /**
     * Creates new form CadAbastecimento
     */
    public CadAbastecimentoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public CadAbastecimentoGUI(java.awt.Frame parent, 
                                boolean modal, 
                                AbastecimentoService abastecimentoService, 
                                FornecedorService fornecedorService, 
                                ProdutoService produtoService, 
                                PessoaService pessoaService, 
                                VeiculoService veiculoService,
                                Usuario usuario, 
                                Empresa empresa) {
        super(parent, modal);
        initComponents();
        setUsuario(usuario);
        setEmpresa(empresa);
        setAbastecimentoService(abastecimentoService);
        setFornecedorService(fornecedorService);
        setProdutoService(produtoService);
        setPessoaService(pessoaService);
        setVeiculoService(veiculoService);
        initComp();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRequisicao = new JTextFieldNumeros(10);
        txtCupom = new JTextFieldNumeros(10);
        btnAddCombustivel = new javax.swing.JButton();
        btnAddFornecedor = new javax.swing.JButton();
        txtQtd = new JNumberField.JNumberField();
        txtValorTot = new JNumberField.JNumberField();
        txtValorUnit = new JNumberField.JNumberField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        dtaDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbPessoa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbVeiculo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtResponse = new JTextFieldLetras(100);
        btnAddPessoa = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Next Software ₢");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(51, 76, 145));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Novo Abastecimento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Dados do Abastecimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fornecedor.:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Combustivel.:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Unitario.:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor Total.:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Quantidade.:");

        jLabel11.setText("Nº Requisição.:");

        jLabel12.setText("Nº Cupom.:");

        txtRequisicao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtCupom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAddCombustivel.setText("+");
        btnAddCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCombustivelActionPerformed(evt);
            }
        });

        btnAddFornecedor.setText("+");
        btnAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFornecedorActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo.:");

        txtId.setEnabled(false);

        dtaDate.setBackground(new java.awt.Color(255, 255, 255));
        dtaDate.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Dta. Abastecimento.:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFornecedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbProduto, 0, 240, Short.MAX_VALUE)
                                    .addComponent(txtRequisicao))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCombustivel)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCupom, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(dtaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFornecedor)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnAddCombustivel)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCupom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtValorTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddCombustivel, cbProduto, jLabel4, jLabel7, txtQtd});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddFornecedor, cbFornecedor, jLabel3});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, txtValorTot, txtValorUnit});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dtaDate, jLabel1, jLabel2, txtId});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Dados do Veiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Proprietário.:");

        cbPessoa.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Veiculo.:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Responsável.:");

        btnAddPessoa.setText("+");
        btnAddPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPessoaActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Observação.:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPessoa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtResponse, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                            .addComponent(cbPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtObs))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAddPessoa)
                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbVeiculo, jLabel10, jLabel9, txtResponse});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddPessoa, cbPessoa, jLabel8});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel14, txtObs});

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Deletar");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setText("Sair");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        erasedComponents();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFornecedorActionPerformed
        CadFornecedorGUI cadFornecedor = new CadFornecedorGUI(null, true, new FornecedorService(), getSession());
        cadFornecedor.setLocationRelativeTo(cadFornecedor);
        cadFornecedor.setVisible(true);
        popFornecedor();
        setFornecedor(cadFornecedor.getFornecedor());
        cbFornecedor.setSelectedItem((Fornecedor) fornecedor);
    }//GEN-LAST:event_btnAddFornecedorActionPerformed

    private void btnAddCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCombustivelActionPerformed
        CadProdutoGUI cadProduto = new CadProdutoGUI(null, true, new ProdutoService(), new CategoriaService(), getSession());
        cadProduto.setLocationRelativeTo(cadProduto);
        cadProduto.setVisible(true);
        popProduto();
        setProduto(cadProduto.getProduto());
        cbProduto.setSelectedItem((Produto) produto);
    }//GEN-LAST:event_btnAddCombustivelActionPerformed

    private void btnAddPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPessoaActionPerformed
        CadPessoaGUI cadPessoa = new CadPessoaGUI(null, true, new PessoaService(), new VeiculoService(), getSession());
        cadPessoa.setLocationRelativeTo(cadPessoa);
        cadPessoa.setVisible(true);
        popVeiculo();
        //setPessoa(cadPessoa.getPessoa());
        //cbPessoa.setSelectedItem((Pessoa) pessoa);
    }//GEN-LAST:event_btnAddPessoaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(verifyComp()){
            save();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(verifyComp()){
            delete();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAbastecimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAbastecimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAbastecimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAbastecimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadAbastecimentoGUI dialog = new CadAbastecimentoGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCombustivel;
    private javax.swing.JButton btnAddFornecedor;
    private javax.swing.JButton btnAddPessoa;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cbFornecedor;
    private javax.swing.JComboBox<Object> cbPessoa;
    private javax.swing.JComboBox<Object> cbProduto;
    private javax.swing.JComboBox<Object> cbVeiculo;
    private com.toedter.calendar.JDateChooser dtaDate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtCupom;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtObs;
    private JNumberField.JNumberField txtQtd;
    private javax.swing.JTextField txtRequisicao;
    private javax.swing.JTextField txtResponse;
    private JNumberField.JNumberField txtValorTot;
    private JNumberField.JNumberField txtValorUnit;
    // End of variables declaration//GEN-END:variables

    private void setIco() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    private Usuario setUsuario(Usuario usuario){
        return this.usuario = usuario;
    }
    private Empresa setEmpresa(Empresa empresa){
        return this.empresa = empresa;
    }
    private AbastecimentoService setAbastecimentoService(AbastecimentoService abastecimentoService){
        return this.abastecimentoService = abastecimentoService;
    }    
    private FornecedorService setFornecedorService(FornecedorService fornecedorService){
        return this.fornecedorService = fornecedorService;
    }
    private ProdutoService setProdutoService(ProdutoService produtoService){
        return this.produtoService = produtoService;
    }
    private PessoaService setPessoaService(PessoaService pessoaService){
        return this.pessoaService = pessoaService;
    }
    private VeiculoService setVeiculoService(VeiculoService veiculoService){
        return this.veiculoService = veiculoService;
    }
    
    private void initComp() {
        setIco();
        popFornecedor();
        popProduto();
        popVeiculo();
        
        txtResponse.setDocument(new UpperCase());
        dtaDate.setDate(new Date());
        dtaDate.requestFocusInWindow();
        
        txtQtd.setNumberFormat(new DecimalFormat("0.000"));
        txtValorUnit.setNumberFormat(new DecimalFormat("0.000"));
        txtValorTot.setNumberFormat(new DecimalFormat("0.000"));
        
        erasedComponents();
                
        cbVeiculo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cbVeiculo.getSelectedItem() != null) {
                    popPessoa();
                }
            }
        });
        
        cbProduto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cbProduto.getSelectedItem() != null) {
                    Produto prod  = (Produto)cbProduto.getSelectedItem();
                    //txtValorUnit.setValue(prod.getValor());                    
                }
            }
        });
        
        txtQtd.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {

                    BigDecimal vQtd = txtQtd.getValue();
                    BigDecimal vUnt = txtValorUnit.getValue();
                    BigDecimal soma = vUnt.multiply(vQtd);
                    txtValorTot.setText(moeda.format(soma));
                }
            }
            @Override
            public void keyReleased(KeyEvent e) {
                String caracteres = ".0987654321";
                if (!caracteres.contains(e.getKeyChar() + "")) {
                    e.consume();
                }
                BigDecimal vQtd = txtQtd.getValue();
                BigDecimal vUnt = txtValorUnit.getValue();
                BigDecimal soma = vUnt.multiply(vQtd); 
                txtValorTot.setText(moeda.format(soma));
            }
        });
        
        txtValorUnit.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {

                    BigDecimal vQtd = txtQtd.getValue();
                    BigDecimal vUnt = txtValorUnit.getValue();
                    BigDecimal soma = vUnt.multiply(vQtd);
                    txtValorTot.setText(moeda.format(soma));
                }
            }
            @Override
            public void keyReleased(KeyEvent e) {
                String caracteres = ".0987654321";
                if (!caracteres.contains(e.getKeyChar() + "")) {
                    e.consume();
                }
                BigDecimal vQtd = txtQtd.getValue();
                BigDecimal vUnt = txtValorUnit.getValue();
                BigDecimal soma = vUnt.multiply(vQtd);
                txtValorTot.setText(moeda.format(soma));
            }
        });
        
        txtValorTot.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {

                    BigDecimal vQtd = txtQtd.getValue();
                    BigDecimal vTot = txtValorTot.getValue();
                    BigDecimal soma = vTot.divide(vQtd, 2, RoundingMode.CEILING);
                    txtValorUnit.setValue(soma);
                }
            }
            @Override
            public void keyReleased(KeyEvent e) {
                String caracteres = ".0987654321";
                if (!caracteres.contains(e.getKeyChar() + "")) {
                    e.consume();
                }
                BigDecimal vQtd = txtQtd.getValue();
                BigDecimal vTot = txtValorTot.getValue();
                BigDecimal soma = vTot.divide(vQtd, 2, RoundingMode.CEILING);
                txtValorUnit.setValue(soma);
            }
        });
    }
    
    private void popVeiculo(){
        if(veiculoService == null){
            JOptionPane.showMessageDialog(this, "VeiculoService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        cbVeiculo.removeAll();
        for(Veiculo p: veiculoService.findAll()){
            cbVeiculo.addItem(p);
        }
        cbVeiculo.setSelectedItem(null);
    }
    
    private void popPessoa(){
        if(pessoaService == null){
            JOptionPane.showMessageDialog(this, "PessoaService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(cbVeiculo.getSelectedItem() != null){
            
            Veiculo veiculo = (Veiculo) cbVeiculo.getSelectedItem();
                       
            cbPessoa.removeAllItems();
            for(Pessoa p : veiculo.getPessoas()){
                cbPessoa.addItem(p);
            }            
            cbPessoa.setSelectedItem(null);
            cbPessoa.setEnabled(true);
            
        }
    }
    
    private void save(){
        completeData();
        if(abastecimentoService == null && abastecimento != null){
            JOptionPane.showMessageDialog(this, "AbastecimentoService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        produto = (Produto) cbProduto.getSelectedItem();
        if(produto.getValor() != txtValorTot.getValue()){
            produto.setValor(txtValorUnit.getValue());

            produtoService.updateSemDialog(produto);            
        }
        abastecimentoService.insertOrUpdate(abastecimento);
        erasedComponents();
    }
    
    private void delete(){
        completeData();
        if(abastecimentoService == null && abastecimento != null){
            JOptionPane.showMessageDialog(this, "AbastecimentoService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        abastecimentoService.insertOrUpdate(abastecimento);
        erasedComponents();
    }
    
    private void completeData(){
        try{
            abastecimento = new Abastecimento();
           
            abastecimento.setId(ParseInteger.tryParseToInt(txtId.getText().trim()));
            abastecimento.setFornecedor((Fornecedor) cbFornecedor.getSelectedItem());
            abastecimento.setProduto((Produto) cbProduto.getSelectedItem());
            abastecimento.setN_requisicao(Integer.parseInt(txtRequisicao.getText()));
            abastecimento.setN_cupom(Integer.parseInt(txtCupom.getText()));
            abastecimento.setPessoa((Pessoa) cbPessoa.getSelectedItem());
            abastecimento.setVeiculo((Veiculo) cbVeiculo.getSelectedItem());
            abastecimento.setResponsavel(txtResponse.getText());
            abastecimento.setQuantidade(txtQtd.getValue());
            abastecimento.setVlr_unitario(txtValorUnit.getValue());    
            abastecimento.setVlr_total(txtValorTot.getValue()); 
            Date date = dtaDate.getDate();
            LocalDate dateF = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            abastecimento.setData_abastecimento(dateF);
            LocalDateTime instante = LocalDateTime.now();
            System.out.println(instante);
            abastecimento.setInstante_lancamento(instante);
            abastecimento.setUsuario(getSession());
            
            if (abastecimento.getId() != null) {
                Abastecimento old = abastecimentoService.findById(abastecimento);
                Empresa emp = old.getEmpresa();
                abastecimento.setEmpresa(emp);
            } else {
                abastecimento.setEmpresa(getEmpresa());
            }
            
            abastecimento.setObservacao(txtObs.getText());

        }catch(NumberFormatException e){
            e.printStackTrace();
            JPaneError.showErrorDialog(null, "Erro ao executar ação!", e);
        }
    }
    
    private void erasedComponents(){
        dtaDate.setDate(new Date());
        cbFornecedor.setSelectedItem(null);
        cbProduto.setSelectedItem(null);
        txtId.setText("");
        txtQtd.setText("");
        txtRequisicao.setText("");
        txtCupom.setText("");
        txtResponse.setText("");
        txtValorUnit.setText("");
        txtValorTot.setText("");
        txtObs.setText("");
        cbProduto.setSelectedItem(null);
        cbVeiculo.setSelectedItem(null);
        cbPessoa.setSelectedItem(null);
        cbPessoa.removeAllItems();
        cbPessoa.setEnabled(false);
        btnDelete.setEnabled(false);
        dtaDate.requestFocusInWindow();
    }
    
    private void popFornecedor(){
        if(fornecedorService == null){
            JOptionPane.showMessageDialog(this, "FornecedorService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cbFornecedor.removeAllItems();
        for(Fornecedor f : fornecedorService.findAll()){
            cbFornecedor.addItem(f);
        }
        cbFornecedor.setSelectedItem(null);
    }
    
    private void popProduto(){
        if(produtoService == null){
            JOptionPane.showMessageDialog(this, "ProdutoService was null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cbProduto.removeAllItems();
        for(Produto f : produtoService.findAll()){
            cbProduto.addItem(f);
        }
        cbProduto.setSelectedItem(null);
    }
     
    
    public void importData(Abastecimento abas){
        if(abas != null){
            abastecimento = abas;
            txtId.setText(String.valueOf(abastecimento.getId()));
            Date date = Date.from(abastecimento.getData_abastecimento().atStartOfDay(ZoneId.systemDefault()).toInstant());
            dtaDate.setDate(date);
            cbFornecedor.setSelectedItem((Fornecedor) abastecimento.getFornecedor());
            cbProduto.setSelectedItem((Produto) abastecimento.getProduto());
            txtQtd.setValue(abastecimento.getQuantidade());
            txtRequisicao.setText(String.valueOf(abastecimento.getN_requisicao()));
            txtCupom.setText(String.valueOf(abastecimento.getN_cupom()));
            txtValorUnit.setValue(abastecimento.getVlr_unitario());
            txtValorTot.setValue(abastecimento.getVlr_total());
            cbVeiculo.setSelectedItem((Veiculo) abastecimento.getVeiculo());
            cbPessoa.setSelectedItem((Pessoa) abastecimento.getPessoa());
            txtResponse.setText(abastecimento.getResponsavel());
            txtObs.setText(abastecimento.getObservacao());
            
            btnDelete.setEnabled(true);
        }
    }
    
    public void setFornecedor(Fornecedor fornecedor){
        this.fornecedor = fornecedor;
    }
    
    public void setProduto(Produto produto){
        this.produto = produto;
    }
    
    public void setPessoa(Pessoa pessoa){
        this.pessoa = pessoa;
    }
    
    private boolean verifyComp(){        
        String err = "";
        if(cbFornecedor.getSelectedItem() == null){
            err += "O campo Fornecedor é obrigatório!\n";
        }
        if(cbProduto.getSelectedItem() == null){
            err += "O campo Combustivel é obrigatório!\n";
        }
        if(txtRequisicao.getText().isEmpty() || txtRequisicao.getText().length() <= 0){
            err += "O campo Nº Requisição  é obrigatório!\n";
        }
        if(txtCupom.getText().isEmpty() || txtCupom.getText().length() <= 0){
            err += "O campo Nº Cupom  é obrigatório!\n";
        }
        if(txtQtd.getText().equals("0,00") || txtQtd.getText().length() <= 0){
            err += "O campo Quantidade é obrigatório!\n";
        }
        if(txtValorUnit.getText().equals("0,00") || txtValorUnit.getText().length() <= 0){
            err += "O campo Valor unitário é obrigatório!\n";
        }
        if(cbPessoa.getSelectedItem() == null){
            err += "O campo Pessoa é obrigatório!\n";
        }
        if(cbVeiculo.getSelectedItem() == null){
            err += "O campo Veiculo é obrigatório!\n";
        }
        if(txtResponse.getText().isEmpty() || txtResponse.getText().length() <= 0){
            err += "O campo Responsável é obrigatório!\n";
        }
        if(err.length() <= 0){
            return true;            
        }else{
            JOptionPane.showMessageDialog(null, err,"FAEDO CAMINHÕES", JOptionPane.ERROR_MESSAGE);
            return false;
        }        
    }

    private Usuario getSession() {
        if (usuario == null) {
            throw new IllegalArgumentException("Usuario was null!");
        }
        return usuario;
    }

    private Empresa getEmpresa() {
        if (empresa == null) {
            throw new IllegalArgumentException("Empresa was null!");
        }
        return empresa;
    }
}
